version: '3.1'

services:
  springboot:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: cchat_scheduler
    ports:
      - 8084:8084
    working_dir: /opt/app
    depends_on:
      - NLU
